name: Elixir CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Restore nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Restore dependencies cache
        uses: actions/cache@v5
        with:
          path: |
            deps
          key: ${{ runner.os }}-mix-${{ env.elixir }}-${{ env.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.elixir }}-${{ env.otp }}-
      - name: Install dependencies
        run: devenv shell --verbose mix do deps.get + deps.compile
      - name: Compile dependencies
        run: devenv shell --verbose mix compile
      - name: Static Analysis & Formatting
        run: devenv shell --verbose mix check --ignore todo
      - name: Check warnings
        run: devenv shell --verbose mix compile --warnings-as-errors
      - name: Run tests
        run: devenv shell --verbose mix test

  release:
    name: Publish to Hex
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Restore nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Restore dependencies cache
        uses: actions/cache@v5
        with:
          path: |
            deps
          key: ${{ runner.os }}-mix-${{ env.elixir }}-${{ env.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.elixir }}-${{ env.otp }}-
      - name: Install dependencies
        run: devenv shell --verbose mix deps.get
      - name: Build in release mode
        run: MIX_ENV=prod devenv shell --verbose mix compile
      - name: Publish to Hex.pm
        run: MIX_ENV=prod devenv shell --verbose mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
